-- ============================================================
-- MAP A (Design Map) - Full SQL Schema & Seed Data
-- ============================================================
-- This file creates the complete Map A database:
--   - design_map_stalls: All stalls for Map A
--   - design_map_reservations: Reservation records for Map A
-- ============================================================

DROP TABLE IF EXISTS design_map_reservations;
DROP TABLE IF EXISTS design_map_stalls;

-- ─────────────────────────────────────────────────────────────
-- Table: design_map_stalls
-- ─────────────────────────────────────────────────────────────
CREATE TABLE design_map_stalls (
  id VARCHAR(8) NOT NULL,
  section VARCHAR(32) NOT NULL,
  number INT NOT NULL DEFAULT 0,
  status VARCHAR(16) NOT NULL DEFAULT 'available',
  price INT NOT NULL DEFAULT 0,
  size VARCHAR(16) NOT NULL DEFAULT 'medium',
  category VARCHAR(64) NOT NULL DEFAULT '',
  description TEXT,
  image_url TEXT,
  reservation_id VARCHAR(64) DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_dms_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ─────────────────────────────────────────────────────────────
-- Table: design_map_reservations
-- ─────────────────────────────────────────────────────────────
CREATE TABLE design_map_reservations (
  id VARCHAR(64) NOT NULL,
  reservation_number VARCHAR(32) NOT NULL,
  stall_id VARCHAR(8) NOT NULL,
  full_name VARCHAR(128) NOT NULL,
  contact_number VARCHAR(32) NOT NULL,
  business_name VARCHAR(128) DEFAULT NULL,
  dti_number VARCHAR(64) DEFAULT NULL,
  cedula_number VARCHAR(64) DEFAULT NULL,
  address TEXT DEFAULT NULL,
  stall_usage_type VARCHAR(64) DEFAULT NULL,
  status VARCHAR(16) NOT NULL DEFAULT 'pending',
  admin_notes TEXT DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  expires_at TIMESTAMP NULL DEFAULT NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_dmr_reservation_number (reservation_number),
  KEY idx_dmr_stall (stall_id),
  KEY idx_dmr_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ─────────────────────────────────────────────────────────────
-- Seed: design_map_stalls (Stalls 1–300 + Corner stalls)
-- ─────────────────────────────────────────────────────────────
-- Images
SET @img_food    = 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=400';
SET @img_veggies = 'https://images.unsplash.com/photo-1540420773420-3366772f4999?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=400';
SET @img_dry     = 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=400';
SET @img_clothing= 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=400';
SET @img_general = 'https://images.unsplash.com/photo-1542838132-92c53300491e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=400';

-- ─── Section A: Stalls 1–47 ────────────────────────────────
INSERT INTO design_map_stalls (id, section, number, status, price, size, category, description, image_url, reservation_id) VALUES
('1',  'Section A', 1,  'available', 1500, 'small',    'Cooked Food',           'Ideal for selling cooked meals, snacks, and Filipino dishes.', @img_food, NULL),
('2',  'Section A', 2,  'available', 2500, 'medium',   'Vegetables & Fruits',   'Spacious stall perfect for fresh vegetables and seasonal produce.', @img_veggies, NULL),
('3',  'Section A', 3,  'available', 2500, 'medium',   'Dry Goods & Groceries', 'Ideal for selling canned goods, condiments, and dry groceries.', @img_dry, NULL),
('4',  'Section A', 4,  'available', 3500, 'large',    'Clothing & Apparel',    'Trendy location for ukay-ukay, ref items, and fashion pieces.', @img_clothing, NULL),
('5',  'Section A', 5,  'available', 2500, 'medium',   'General Merchandise',   'Versatile stall for hardware, tools, and household items.', @img_general, NULL),
('6',  'Section A', 6,  'available', 1500, 'small',    'Cooked Food',           'Perfect spot for a carinderia or food stall near the main aisle.', @img_food, NULL),
('7',  'Section A', 7,  'available', 2500, 'medium',   'Vegetables & Fruits',   'Conveniently located near the entrance for easy customer access.', @img_veggies, NULL),
('8',  'Section A', 8,  'available', 2500, 'medium',   'Dry Goods & Groceries', 'Large stall suitable for wholesale and retail dry goods.', @img_dry, NULL),
('9',  'Section A', 9,  'available', 3500, 'large',    'Clothing & Apparel',    'Perfect for selling everyday clothing and accessories.', @img_clothing, NULL),
('10', 'Section A', 10, 'available', 2500, 'medium',   'General Merchandise',   'Ideal for selling electronics, phone accessories, and gadgets.', @img_general, NULL),
('11', 'Section A', 11, 'available', 1500, 'small',    'Cooked Food',           'High-traffic location great for fast food and ready-to-eat items.', @img_food, NULL),
('12', 'Section A', 12, 'available', 2500, 'medium',   'Vegetables & Fruits',   'Great for fruits, vegetables, herbs, and fresh condiments.', @img_veggies, NULL),
('13', 'Section A', 13, 'available', 2500, 'medium',   'Dry Goods & Groceries', 'Perfect for rice, flour, sugar, salt, and pantry essentials.', @img_dry, NULL),
('14', 'Section A', 14, 'available', 3500, 'large',    'Clothing & Apparel',    'Ideal for school uniforms, casual wear, and workwear.', @img_clothing, NULL),
('15', 'Section A', 15, 'available', 2500, 'medium',   'General Merchandise',   'Perfect for kitchenware, cookware, and home essentials.', @img_general, NULL),
('16', 'Section A', 16, 'available', 1500, 'small',    'Cooked Food',           'Corner stall with extra space for cooking equipment and display.', @img_food, NULL),
('17', 'Section A', 17, 'reserved',  2500, 'medium',   'Vegetables & Fruits',   'Well-ventilated space ideal for fresh tropical fruits.', @img_veggies, NULL),
('18', 'Section A', 18, 'available', 2500, 'medium',   'Dry Goods & Groceries', 'Great for spices, seasonings, and cooking ingredients.', @img_dry, NULL),
('19', 'Section A', 19, 'available', 3500, 'large',    'Clothing & Apparel',    'Great spot for selling bags, shoes, and fashion accessories.', @img_clothing, NULL),
('20', 'Section A', 20, 'available', 2500, 'medium',   'General Merchandise',   'Great for personal care products and hygiene goods.', @img_general, NULL),
('21', 'Section A', 21, 'available', 1500, 'small',    'Cooked Food',           'Suitable for selling breakfast meals, kakanin, and beverages.', @img_food, NULL),
('22', 'Section A', 22, 'available', 2500, 'medium',   'Vegetables & Fruits',   'Corner stall with wide display area for colorful produce.', @img_veggies, NULL),
('23', 'Section A', 23, 'available', 2500, 'medium',   'Dry Goods & Groceries', 'Corner location with high foot traffic, ideal for grocery items.', @img_dry, NULL),
('24', 'Section A', 24, 'available', 3500, 'large',    'Clothing & Apparel',    'Corner stall with extra space for hanging clothes and display.', @img_clothing, NULL),
('25', 'Section A', 25, 'available', 2500, 'medium',   'General Merchandise',   'Corner stall with wide space for displaying varied merchandise.', @img_general, NULL),
('26', 'Section A', 26, 'available', 1500, 'small',    'Cooked Food',           'Great for silog meals, merienda, and affordable daily lunches.', @img_food, NULL),
('27', 'Section A', 27, 'available', 2500, 'medium',   'Vegetables & Fruits',   'Suitable for exotic fruits, organic veggies, and fresh herbs.', @img_veggies, NULL),
('28', 'Section A', 28, 'available', 2500, 'medium',   'Dry Goods & Groceries', 'Suitable for noodles, crackers, biscuits, and packaged foods.', @img_dry, NULL),
('29', 'Section A', 29, 'occupied',  3500, 'large',    'Clothing & Apparel',    'High-visibility location for fashion retail and trendy items.', @img_clothing, NULL),
('30', 'Section A', 30, 'available', 2500, 'medium',   'General Merchandise',   'Suitable for school supplies, notebooks, and art materials.', @img_general, NULL),
('31', 'Section A', 31, 'available', 1500, 'small',    'Cooked Food',           'Prime location for barbecue, grilled items, and pulutan.', @img_food, NULL),
('32', 'Section A', 32, 'available', 2500, 'medium',   'Vegetables & Fruits',   'Near the wet section, ideal for root crops and leafy greens.', @img_veggies, NULL),
('33', 'Section A', 33, 'available', 2500, 'medium',   'Dry Goods & Groceries', 'Excellent for coffee, sugar, and everyday household needs.', @img_dry, NULL),
('34', 'Section A', 34, 'available', 3500, 'large',    'Clothing & Apparel',    "Suitable for children's clothing, school supplies, and toys.", @img_clothing, NULL),
('35', 'Section A', 35, 'available', 2500, 'medium',   'General Merchandise',   'Excellent for seeds, gardening tools, and farm supplies.', @img_general, NULL),
('36', 'Section A', 36, 'available', 1500, 'small',    'Cooked Food',           'Excellent for baked goods, pastries, and Filipino desserts.', @img_food, NULL),
('37', 'Section A', 37, 'available', 2500, 'medium',   'Vegetables & Fruits',   'Prime spot for selling locally sourced farm produce.', @img_veggies, NULL),
('38', 'Section A', 38, 'available', 2500, 'medium',   'Dry Goods & Groceries', 'Wide display space for organizing dry goods and groceries.', @img_dry, NULL),
('39', 'Section A', 39, 'available', 3500, 'large',    'Clothing & Apparel',    'Excellent for local designer pieces and handcrafted goods.', @img_clothing, NULL),
('40', 'Section A', 40, 'available', 2500, 'medium',   'General Merchandise',   'Wide-open stall ideal for wholesale general goods.', @img_general, NULL),
('41', 'Section A', 41, 'available', 1500, 'small',    'Cooked Food',           'Ideal for selling cooked meals, snacks, and Filipino dishes.', @img_food, NULL),
('42', 'Section A', 42, 'available', 2500, 'medium',   'Vegetables & Fruits',   'Spacious stall perfect for fresh vegetables and seasonal produce.', @img_veggies, NULL),
('43', 'Section A', 43, 'available', 2500, 'medium',   'Dry Goods & Groceries', 'Ideal for selling canned goods, condiments, and dry groceries.', @img_dry, NULL),
('44', 'Section A', 44, 'available', 3500, 'large',    'Clothing & Apparel',    'Trendy location for ukay-ukay, ref items, and fashion pieces.', @img_clothing, NULL),
('45', 'Section A', 45, 'available', 2500, 'medium',   'General Merchandise',   'Versatile stall for hardware, tools, and household items.', @img_general, NULL),
('46', 'Section A', 46, 'available', 1500, 'small',    'Cooked Food',           'Perfect spot for a carinderia or food stall near the main aisle.', @img_food, NULL),
('47', 'Section A', 47, 'available', 2500, 'medium',   'Vegetables & Fruits',   'Conveniently located near the entrance for easy customer access.', @img_veggies, NULL);

-- ─── Section B: Stalls 48–91 ────────────────────────────────
INSERT INTO design_map_stalls (id, section, number, status, price, size, category, description, image_url, reservation_id) VALUES
('48', 'Section B', 48, 'available', 2500, 'medium', 'Dry Goods & Groceries', 'Large stall suitable for wholesale and retail dry goods.', @img_dry, NULL),
('49', 'Section B', 49, 'available', 3500, 'large',  'Clothing & Apparel',    'Perfect for selling everyday clothing and accessories.', @img_clothing, NULL),
('50', 'Section B', 50, 'available', 2500, 'medium', 'General Merchandise',   'Ideal for selling electronics, phone accessories, and gadgets.', @img_general, NULL),
('51', 'Section B', 51, 'available', 1500, 'small',  'Cooked Food',           'High-traffic location great for fast food and ready-to-eat items.', @img_food, NULL),
('52', 'Section B', 52, 'available', 2500, 'medium', 'Vegetables & Fruits',   'Great for fruits, vegetables, herbs, and fresh condiments.', @img_veggies, NULL),
('53', 'Section B', 53, 'available', 2500, 'medium', 'Dry Goods & Groceries', 'Perfect for rice, flour, sugar, salt, and pantry essentials.', @img_dry, NULL),
('54', 'Section B', 54, 'available', 3500, 'large',  'Clothing & Apparel',    'Ideal for school uniforms, casual wear, and workwear.', @img_clothing, NULL),
('55', 'Section B', 55, 'available', 2500, 'medium', 'General Merchandise',   'Perfect for kitchenware, cookware, and home essentials.', @img_general, NULL),
('56', 'Section B', 56, 'available', 1500, 'small',  'Cooked Food',           'Corner stall with extra space for cooking equipment and display.', @img_food, NULL),
('57', 'Section B', 57, 'reserved',  2500, 'medium', 'Vegetables & Fruits',   'Well-ventilated space ideal for fresh tropical fruits.', @img_veggies, NULL),
('58', 'Section B', 58, 'available', 2500, 'medium', 'Dry Goods & Groceries', 'Great for spices, seasonings, and cooking ingredients.', @img_dry, NULL),
('59', 'Section B', 59, 'available', 3500, 'large',  'Clothing & Apparel',    'Great spot for selling bags, shoes, and fashion accessories.', @img_clothing, NULL),
('60', 'Section B', 60, 'available', 2500, 'medium', 'General Merchandise',   'Great for personal care products and hygiene goods.', @img_general, NULL),
('61', 'Section B', 61, 'available', 1500, 'small',  'Cooked Food',           'Suitable for selling breakfast meals, kakanin, and beverages.', @img_food, NULL),
('62', 'Section B', 62, 'available', 2500, 'medium', 'Vegetables & Fruits',   'Corner stall with wide display area for colorful produce.', @img_veggies, NULL),
('63', 'Section B', 63, 'available', 2500, 'medium', 'Dry Goods & Groceries', 'Corner location with high foot traffic, ideal for grocery items.', @img_dry, NULL),
('64', 'Section B', 64, 'available', 3500, 'large',  'Clothing & Apparel',    'Corner stall with extra space for hanging clothes and display.', @img_clothing, NULL),
('65', 'Section B', 65, 'available', 2500, 'medium', 'General Merchandise',   'Corner stall with wide space for displaying varied merchandise.', @img_general, NULL),
('66', 'Section B', 66, 'available', 1500, 'small',  'Cooked Food',           'Great for silog meals, merienda, and affordable daily lunches.', @img_food, NULL),
('67', 'Section B', 67, 'available', 2500, 'medium', 'Vegetables & Fruits',   'Suitable for exotic fruits, organic veggies, and fresh herbs.', @img_veggies, NULL),
('68', 'Section B', 68, 'available', 2500, 'medium', 'Dry Goods & Groceries', 'Suitable for noodles, crackers, biscuits, and packaged foods.', @img_dry, NULL),
('69', 'Section B', 69, 'available', 3500, 'large',  'Clothing & Apparel',    'High-visibility location for fashion retail and trendy items.', @img_clothing, NULL),
('70', 'Section B', 70, 'available', 2500, 'medium', 'General Merchandise',   'Suitable for school supplies, notebooks, and art materials.', @img_general, NULL),
('71', 'Section B', 71, 'available', 1500, 'small',  'Cooked Food',           'Prime location for barbecue, grilled items, and pulutan.', @img_food, NULL),
('72', 'Section B', 72, 'available', 2500, 'medium', 'Vegetables & Fruits',   'Near the wet section, ideal for root crops and leafy greens.', @img_veggies, NULL),
('73', 'Section B', 73, 'available', 2500, 'medium', 'Dry Goods & Groceries', 'Excellent for coffee, sugar, and everyday household needs.', @img_dry, NULL),
('74', 'Section B', 74, 'available', 3500, 'large',  'Clothing & Apparel',    "Suitable for children's clothing, school supplies, and toys.", @img_clothing, NULL),
('75', 'Section B', 75, 'available', 2500, 'medium', 'General Merchandise',   'Excellent for seeds, gardening tools, and farm supplies.', @img_general, NULL),
('76', 'Section B', 76, 'available', 1500, 'small',  'Cooked Food',           'Excellent for baked goods, pastries, and Filipino desserts.', @img_food, NULL),
('77', 'Section B', 77, 'available', 2500, 'medium', 'Vegetables & Fruits',   'Prime spot for selling locally sourced farm produce.', @img_veggies, NULL),
('78', 'Section B', 78, 'available', 2500, 'medium', 'Dry Goods & Groceries', 'Wide display space for organizing dry goods and groceries.', @img_dry, NULL),
('79', 'Section B', 79, 'available', 3500, 'large',  'Clothing & Apparel',    'Excellent for local designer pieces and handcrafted goods.', @img_clothing, NULL),
('80', 'Section B', 80, 'available', 2500, 'medium', 'General Merchandise',   'Wide-open stall ideal for wholesale general goods.', @img_general, NULL),
('81', 'Section B', 81, 'available', 1500, 'small',  'Cooked Food',           'Ideal for selling cooked meals, snacks, and Filipino dishes.', @img_food, NULL),
('82', 'Section B', 82, 'available', 2500, 'medium', 'Vegetables & Fruits',   'Spacious stall perfect for fresh vegetables and seasonal produce.', @img_veggies, NULL),
('83', 'Section B', 83, 'available', 2500, 'medium', 'Dry Goods & Groceries', 'Ideal for selling canned goods, condiments, and dry groceries.', @img_dry, NULL),
('84', 'Section B', 84, 'available', 3500, 'large',  'Clothing & Apparel',    'Trendy location for ukay-ukay, ref items, and fashion pieces.', @img_clothing, NULL),
('85', 'Section B', 85, 'available', 2500, 'medium', 'General Merchandise',   'Versatile stall for hardware, tools, and household items.', @img_general, NULL),
('86', 'Section B', 86, 'available', 1500, 'small',  'Cooked Food',           'Perfect spot for a carinderia or food stall near the main aisle.', @img_food, NULL),
('87', 'Section B', 87, 'available', 2500, 'medium', 'Vegetables & Fruits',   'Conveniently located near the entrance for easy customer access.', @img_veggies, NULL),
('88', 'Section B', 88, 'available', 2500, 'medium', 'Dry Goods & Groceries', 'Large stall suitable for wholesale and retail dry goods.', @img_dry, NULL),
('89', 'Section B', 89, 'available', 3500, 'large',  'Clothing & Apparel',    'Perfect for selling everyday clothing and accessories.', @img_clothing, NULL),
('90', 'Section B', 90, 'available', 2500, 'medium', 'General Merchandise',   'Ideal for selling electronics, phone accessories, and gadgets.', @img_general, NULL),
('91', 'Section B', 91, 'available', 1500, 'small',  'Cooked Food',           'High-traffic location great for fast food and ready-to-eat items.', @img_food, NULL);

-- ─── Section AA: Stalls 92–133 ──────────────────────────────
INSERT INTO design_map_stalls (id, section, number, status, price, size, category, description, image_url, reservation_id) VALUES
('92',  'Section AA', 92,  'available', 2500, 'medium', 'Vegetables & Fruits',   'Great for fruits, vegetables, herbs, and fresh condiments.', @img_veggies, NULL),
('93',  'Section AA', 93,  'available', 2500, 'medium', 'Dry Goods & Groceries', 'Perfect for rice, flour, sugar, salt, and pantry essentials.', @img_dry, NULL),
('94',  'Section AA', 94,  'available', 3500, 'large',  'Clothing & Apparel',    'Ideal for school uniforms, casual wear, and workwear.', @img_clothing, NULL),
('95',  'Section AA', 95,  'available', 2500, 'medium', 'General Merchandise',   'Perfect for kitchenware, cookware, and home essentials.', @img_general, NULL),
('96',  'Section AA', 96,  'available', 1500, 'small',  'Cooked Food',           'Corner stall with extra space for cooking equipment and display.', @img_food, NULL),
('97',  'Section AA', 97,  'reserved',  2500, 'medium', 'Vegetables & Fruits',   'Well-ventilated space ideal for fresh tropical fruits.', @img_veggies, NULL),
('98',  'Section AA', 98,  'available', 2500, 'medium', 'Dry Goods & Groceries', 'Great for spices, seasonings, and cooking ingredients.', @img_dry, NULL),
('99',  'Section AA', 99,  'available', 3500, 'large',  'Clothing & Apparel',    'Great spot for selling bags, shoes, and fashion accessories.', @img_clothing, NULL),
('100', 'Section AA', 100, 'available', 2500, 'medium', 'General Merchandise',   'Great for personal care products and hygiene goods.', @img_general, NULL),
('101', 'Section AA', 101, 'available', 1500, 'small',  'Cooked Food',           'Suitable for selling breakfast meals, kakanin, and beverages.', @img_food, NULL),
('102', 'Section AA', 102, 'available', 2500, 'medium', 'Vegetables & Fruits',   'Corner stall with wide display area for colorful produce.', @img_veggies, NULL),
('103', 'Section AA', 103, 'available', 2500, 'medium', 'Dry Goods & Groceries', 'Corner location with high foot traffic, ideal for grocery items.', @img_dry, NULL),
('104', 'Section AA', 104, 'available', 3500, 'large',  'Clothing & Apparel',    'Corner stall with extra space for hanging clothes and display.', @img_clothing, NULL),
('105', 'Section AA', 105, 'available', 2500, 'medium', 'General Merchandise',   'Corner stall with wide space for displaying varied merchandise.', @img_general, NULL),
('106', 'Section AA', 106, 'available', 1500, 'small',  'Cooked Food',           'Great for silog meals, merienda, and affordable daily lunches.', @img_food, NULL),
('107', 'Section AA', 107, 'available', 2500, 'medium', 'Vegetables & Fruits',   'Suitable for exotic fruits, organic veggies, and fresh herbs.', @img_veggies, NULL),
('108', 'Section AA', 108, 'available', 2500, 'medium', 'Dry Goods & Groceries', 'Suitable for noodles, crackers, biscuits, and packaged foods.', @img_dry, NULL),
('109', 'Section AA', 109, 'available', 3500, 'large',  'Clothing & Apparel',    'High-visibility location for fashion retail and trendy items.', @img_clothing, NULL),
('110', 'Section AA', 110, 'available', 2500, 'medium', 'General Merchandise',   'Suitable for school supplies, notebooks, and art materials.', @img_general, NULL),
('111', 'Section AA', 111, 'available', 1500, 'small',  'Cooked Food',           'Prime location for barbecue, grilled items, and pulutan.', @img_food, NULL),
('112', 'Section AA', 112, 'available', 2500, 'medium', 'Vegetables & Fruits',   'Near the wet section, ideal for root crops and leafy greens.', @img_veggies, NULL),
('113', 'Section AA', 113, 'available', 2500, 'medium', 'Dry Goods & Groceries', 'Excellent for coffee, sugar, and everyday household needs.', @img_dry, NULL),
('114', 'Section AA', 114, 'available', 3500, 'large',  'Clothing & Apparel',    "Suitable for children's clothing, school supplies, and toys.", @img_clothing, NULL),
('115', 'Section AA', 115, 'available', 2500, 'medium', 'General Merchandise',   'Excellent for seeds, gardening tools, and farm supplies.', @img_general, NULL),
('116', 'Section AA', 116, 'available', 1500, 'small',  'Cooked Food',           'Excellent for baked goods, pastries, and Filipino desserts.', @img_food, NULL),
('117', 'Section AA', 117, 'available', 2500, 'medium', 'Vegetables & Fruits',   'Prime spot for selling locally sourced farm produce.', @img_veggies, NULL),
('118', 'Section AA', 118, 'available', 2500, 'medium', 'Dry Goods & Groceries', 'Wide display space for organizing dry goods and groceries.', @img_dry, NULL),
('119', 'Section AA', 119, 'available', 3500, 'large',  'Clothing & Apparel',    'Excellent for local designer pieces and handcrafted goods.', @img_clothing, NULL),
('120', 'Section AA', 120, 'available', 2500, 'medium', 'General Merchandise',   'Wide-open stall ideal for wholesale general goods.', @img_general, NULL),
('121', 'Section AA', 121, 'available', 1500, 'small',  'Cooked Food',           'Ideal for selling cooked meals, snacks, and Filipino dishes.', @img_food, NULL),
('122', 'Section AA', 122, 'available', 2500, 'medium', 'Vegetables & Fruits',   'Spacious stall perfect for fresh vegetables and seasonal produce.', @img_veggies, NULL),
('123', 'Section AA', 123, 'available', 2500, 'medium', 'Dry Goods & Groceries', 'Ideal for selling canned goods, condiments, and dry groceries.', @img_dry, NULL),
('124', 'Section AA', 124, 'available', 3500, 'large',  'Clothing & Apparel',    'Trendy location for ukay-ukay, ref items, and fashion pieces.', @img_clothing, NULL),
('125', 'Section AA', 125, 'available', 2500, 'medium', 'General Merchandise',   'Versatile stall for hardware, tools, and household items.', @img_general, NULL),
('126', 'Section AA', 126, 'available', 1500, 'small',  'Cooked Food',           'Perfect spot for a carinderia or food stall near the main aisle.', @img_food, NULL),
('127', 'Section AA', 127, 'available', 2500, 'medium', 'Vegetables & Fruits',   'Conveniently located near the entrance for easy customer access.', @img_veggies, NULL),
('128', 'Section AA', 128, 'available', 2500, 'medium', 'Dry Goods & Groceries', 'Large stall suitable for wholesale and retail dry goods.', @img_dry, NULL),
('129', 'Section AA', 129, 'available', 3500, 'large',  'Clothing & Apparel',    'Perfect for selling everyday clothing and accessories.', @img_clothing, NULL),
('130', 'Section AA', 130, 'available', 2500, 'medium', 'General Merchandise',   'Ideal for selling electronics, phone accessories, and gadgets.', @img_general, NULL),
('131', 'Section AA', 131, 'available', 1500, 'small',  'Cooked Food',           'High-traffic location great for fast food and ready-to-eat items.', @img_food, NULL),
('132', 'Section AA', 132, 'available', 2500, 'medium', 'Vegetables & Fruits',   'Great for fruits, vegetables, herbs, and fresh condiments.', @img_veggies, NULL),
('133', 'Section AA', 133, 'available', 2500, 'medium', 'Dry Goods & Groceries', 'Perfect for rice, flour, sugar, salt, and pantry essentials.', @img_dry, NULL);

-- ─── Section BB: Stalls 134–167 ─────────────────────────────
INSERT INTO design_map_stalls (id, section, number, status, price, size, category, description, image_url, reservation_id) VALUES
('134', 'Section BB', 134, 'available', 3500, 'large',  'Clothing & Apparel',    'Ideal for school uniforms, casual wear, and workwear.', @img_clothing, NULL),
('135', 'Section BB', 135, 'available', 2500, 'medium', 'General Merchandise',   'Perfect for kitchenware, cookware, and home essentials.', @img_general, NULL),
('136', 'Section BB', 136, 'available', 1500, 'small',  'Cooked Food',           'Corner stall with extra space for cooking equipment and display.', @img_food, NULL),
('137', 'Section BB', 137, 'reserved',  2500, 'medium', 'Vegetables & Fruits',   'Well-ventilated space ideal for fresh tropical fruits.', @img_veggies, NULL),
('138', 'Section BB', 138, 'available', 2500, 'medium', 'Dry Goods & Groceries', 'Great for spices, seasonings, and cooking ingredients.', @img_dry, NULL),
('139', 'Section BB', 139, 'available', 3500, 'large',  'Clothing & Apparel',    'Great spot for selling bags, shoes, and fashion accessories.', @img_clothing, NULL),
('140', 'Section BB', 140, 'available', 2500, 'medium', 'General Merchandise',   'Great for personal care products and hygiene goods.', @img_general, NULL),
('141', 'Section BB', 141, 'available', 1500, 'small',  'Cooked Food',           'Suitable for selling breakfast meals, kakanin, and beverages.', @img_food, NULL),
('142', 'Section BB', 142, 'available', 2500, 'medium', 'Vegetables & Fruits',   'Corner stall with wide display area for colorful produce.', @img_veggies, NULL),
('143', 'Section BB', 143, 'available', 2500, 'medium', 'Dry Goods & Groceries', 'Corner location with high foot traffic, ideal for grocery items.', @img_dry, NULL),
('144', 'Section BB', 144, 'available', 3500, 'large',  'Clothing & Apparel',    'Corner stall with extra space for hanging clothes and display.', @img_clothing, NULL),
('145', 'Section BB', 145, 'available', 2500, 'medium', 'General Merchandise',   'Corner stall with wide space for displaying varied merchandise.', @img_general, NULL),
('146', 'Section BB', 146, 'available', 1500, 'small',  'Cooked Food',           'Great for silog meals, merienda, and affordable daily lunches.', @img_food, NULL),
('147', 'Section BB', 147, 'available', 2500, 'medium', 'Vegetables & Fruits',   'Suitable for exotic fruits, organic veggies, and fresh herbs.', @img_veggies, NULL),
('148', 'Section BB', 148, 'available', 2500, 'medium', 'Dry Goods & Groceries', 'Suitable for noodles, crackers, biscuits, and packaged foods.', @img_dry, NULL),
('149', 'Section BB', 149, 'available', 3500, 'large',  'Clothing & Apparel',    'High-visibility location for fashion retail and trendy items.', @img_clothing, NULL),
('150', 'Section BB', 150, 'available', 2500, 'medium', 'General Merchandise',   'Suitable for school supplies, notebooks, and art materials.', @img_general, NULL),
('151', 'Section BB', 151, 'available', 1500, 'small',  'Cooked Food',           'Prime location for barbecue, grilled items, and pulutan.', @img_food, NULL),
('152', 'Section BB', 152, 'available', 2500, 'medium', 'Vegetables & Fruits',   'Near the wet section, ideal for root crops and leafy greens.', @img_veggies, NULL),
('153', 'Section BB', 153, 'available', 2500, 'medium', 'Dry Goods & Groceries', 'Excellent for coffee, sugar, and everyday household needs.', @img_dry, NULL),
('154', 'Section BB', 154, 'available', 3500, 'large',  'Clothing & Apparel',    "Suitable for children's clothing, school supplies, and toys.", @img_clothing, NULL),
('155', 'Section BB', 155, 'available', 2500, 'medium', 'General Merchandise',   'Excellent for seeds, gardening tools, and farm supplies.', @img_general, NULL),
('156', 'Section BB', 156, 'available', 1500, 'small',  'Cooked Food',           'Excellent for baked goods, pastries, and Filipino desserts.', @img_food, NULL),
('157', 'Section BB', 157, 'available', 2500, 'medium', 'Vegetables & Fruits',   'Prime spot for selling locally sourced farm produce.', @img_veggies, NULL),
('158', 'Section BB', 158, 'available', 2500, 'medium', 'Dry Goods & Groceries', 'Wide display space for organizing dry goods and groceries.', @img_dry, NULL),
('159', 'Section BB', 159, 'available', 3500, 'large',  'Clothing & Apparel',    'Excellent for local designer pieces and handcrafted goods.', @img_clothing, NULL),
('160', 'Section BB', 160, 'available', 2500, 'medium', 'General Merchandise',   'Wide-open stall ideal for wholesale general goods.', @img_general, NULL),
('161', 'Section BB', 161, 'available', 1500, 'small',  'Cooked Food',           'Ideal for selling cooked meals, snacks, and Filipino dishes.', @img_food, NULL),
('162', 'Section BB', 162, 'available', 2500, 'medium', 'Vegetables & Fruits',   'Spacious stall perfect for fresh vegetables and seasonal produce.', @img_veggies, NULL),
('163', 'Section BB', 163, 'available', 2500, 'medium', 'Dry Goods & Groceries', 'Ideal for selling canned goods, condiments, and dry groceries.', @img_dry, NULL),
('164', 'Section BB', 164, 'available', 3500, 'large',  'Clothing & Apparel',    'Trendy location for ukay-ukay, ref items, and fashion pieces.', @img_clothing, NULL),
('165', 'Section BB', 165, 'available', 2500, 'medium', 'General Merchandise',   'Versatile stall for hardware, tools, and household items.', @img_general, NULL),
('166', 'Section BB', 166, 'available', 1500, 'small',  'Cooked Food',           'Perfect spot for a carinderia or food stall near the main aisle.', @img_food, NULL),
('167', 'Section BB', 167, 'available', 2500, 'medium', 'Vegetables & Fruits',   'Conveniently located near the entrance for easy customer access.', @img_veggies, NULL);

-- ─── Section C: Stalls 168–204 (General Merchandise) ────────
INSERT INTO design_map_stalls (id, section, number, status, price, size, category, description, image_url, reservation_id) VALUES
('168', 'Section C', 168, 'available', 2500, 'medium', 'General Merchandise', 'Versatile stall for hardware, tools, and household items.', @img_general, NULL),
('169', 'Section C', 169, 'available', 2500, 'medium', 'General Merchandise', 'Ideal for selling electronics, phone accessories, and gadgets.', @img_general, NULL),
('170', 'Section C', 170, 'available', 2500, 'medium', 'General Merchandise', 'Perfect for kitchenware, cookware, and home essentials.', @img_general, NULL),
('171', 'Section C', 171, 'available', 2500, 'medium', 'General Merchandise', 'Great for personal care products and hygiene goods.', @img_general, NULL),
('172', 'Section C', 172, 'available', 2500, 'medium', 'General Merchandise', 'Corner stall with wide space for displaying varied merchandise.', @img_general, NULL),
('173', 'Section C', 173, 'available', 2500, 'medium', 'General Merchandise', 'Suitable for school supplies, notebooks, and art materials.', @img_general, NULL),
('174', 'Section C', 174, 'available', 2500, 'medium', 'General Merchandise', 'Excellent for seeds, gardening tools, and farm supplies.', @img_general, NULL),
('175', 'Section C', 175, 'available', 2500, 'medium', 'General Merchandise', 'Wide-open stall ideal for wholesale general goods.', @img_general, NULL),
('176', 'Section C', 176, 'available', 2500, 'medium', 'General Merchandise', 'Versatile stall for hardware, tools, and household items.', @img_general, NULL),
('177', 'Section C', 177, 'reserved',  2500, 'medium', 'General Merchandise', 'Ideal for selling electronics, phone accessories, and gadgets.', @img_general, NULL),
('178', 'Section C', 178, 'available', 2500, 'medium', 'General Merchandise', 'Perfect for kitchenware, cookware, and home essentials.', @img_general, NULL),
('179', 'Section C', 179, 'available', 2500, 'medium', 'General Merchandise', 'Great for personal care products and hygiene goods.', @img_general, NULL),
('180', 'Section C', 180, 'available', 2500, 'medium', 'General Merchandise', 'Corner stall with wide space for displaying varied merchandise.', @img_general, NULL),
('181', 'Section C', 181, 'available', 2500, 'medium', 'General Merchandise', 'Suitable for school supplies, notebooks, and art materials.', @img_general, NULL),
('182', 'Section C', 182, 'available', 2500, 'medium', 'General Merchandise', 'Excellent for seeds, gardening tools, and farm supplies.', @img_general, NULL),
('183', 'Section C', 183, 'available', 2500, 'medium', 'General Merchandise', 'Wide-open stall ideal for wholesale general goods.', @img_general, NULL),
('184', 'Section C', 184, 'available', 2500, 'medium', 'General Merchandise', 'Versatile stall for hardware, tools, and household items.', @img_general, NULL),
('185', 'Section C', 185, 'available', 2500, 'medium', 'General Merchandise', 'Ideal for selling electronics, phone accessories, and gadgets.', @img_general, NULL),
('186', 'Section C', 186, 'available', 2500, 'medium', 'General Merchandise', 'Perfect for kitchenware, cookware, and home essentials.', @img_general, NULL),
('187', 'Section C', 187, 'available', 2500, 'medium', 'General Merchandise', 'Great for personal care products and hygiene goods.', @img_general, NULL),
('188', 'Section C', 188, 'available', 2500, 'medium', 'General Merchandise', 'Corner stall with wide space for displaying varied merchandise.', @img_general, NULL),
('189', 'Section C', 189, 'available', 2500, 'medium', 'General Merchandise', 'Suitable for school supplies, notebooks, and art materials.', @img_general, NULL),
('190', 'Section C', 190, 'available', 2500, 'medium', 'General Merchandise', 'Excellent for seeds, gardening tools, and farm supplies.', @img_general, NULL),
('191', 'Section C', 191, 'available', 2500, 'medium', 'General Merchandise', 'Wide-open stall ideal for wholesale general goods.', @img_general, NULL),
('192', 'Section C', 192, 'occupied',  2500, 'medium', 'General Merchandise', 'Versatile stall for hardware, tools, and household items.', @img_general, NULL),
('193', 'Section C', 193, 'available', 2500, 'medium', 'General Merchandise', 'Ideal for selling electronics, phone accessories, and gadgets.', @img_general, NULL),
('194', 'Section C', 194, 'available', 2500, 'medium', 'General Merchandise', 'Perfect for kitchenware, cookware, and home essentials.', @img_general, NULL),
('195', 'Section C', 195, 'available', 2500, 'medium', 'General Merchandise', 'Great for personal care products and hygiene goods.', @img_general, NULL),
('196', 'Section C', 196, 'available', 2500, 'medium', 'General Merchandise', 'Corner stall with wide space for displaying varied merchandise.', @img_general, NULL),
('197', 'Section C', 197, 'available', 2500, 'medium', 'General Merchandise', 'Suitable for school supplies, notebooks, and art materials.', @img_general, NULL),
('198', 'Section C', 198, 'available', 2500, 'medium', 'General Merchandise', 'Excellent for seeds, gardening tools, and farm supplies.', @img_general, NULL),
('199', 'Section C', 199, 'available', 2500, 'medium', 'General Merchandise', 'Wide-open stall ideal for wholesale general goods.', @img_general, NULL),
('200', 'Section C', 200, 'available', 2500, 'medium', 'General Merchandise', 'Versatile stall for hardware, tools, and household items.', @img_general, NULL),
('201', 'Section C', 201, 'available', 2500, 'medium', 'General Merchandise', 'Ideal for selling electronics, phone accessories, and gadgets.', @img_general, NULL),
('202', 'Section C', 202, 'available', 2500, 'medium', 'General Merchandise', 'Perfect for kitchenware, cookware, and home essentials.', @img_general, NULL),
('203', 'Section C', 203, 'available', 2500, 'medium', 'General Merchandise', 'Great for personal care products and hygiene goods.', @img_general, NULL),
('204', 'Section C', 204, 'available', 2500, 'medium', 'General Merchandise', 'Corner stall with wide space for displaying varied merchandise.', @img_general, NULL);

-- ─── Section D: Stalls 205–243 (General Merchandise) ────────
INSERT INTO design_map_stalls (id, section, number, status, price, size, category, description, image_url, reservation_id) VALUES
('205', 'Section D', 205, 'available', 2500, 'medium', 'General Merchandise', 'Suitable for school supplies, notebooks, and art materials.', @img_general, NULL),
('206', 'Section D', 206, 'available', 2500, 'medium', 'General Merchandise', 'Excellent for seeds, gardening tools, and farm supplies.', @img_general, NULL),
('207', 'Section D', 207, 'available', 2500, 'medium', 'General Merchandise', 'Wide-open stall ideal for wholesale general goods.', @img_general, NULL),
('208', 'Section D', 208, 'available', 2500, 'medium', 'General Merchandise', 'Versatile stall for hardware, tools, and household items.', @img_general, NULL),
('209', 'Section D', 209, 'available', 2500, 'medium', 'General Merchandise', 'Ideal for selling electronics, phone accessories, and gadgets.', @img_general, NULL),
('210', 'Section D', 210, 'available', 2500, 'medium', 'General Merchandise', 'Perfect for kitchenware, cookware, and home essentials.', @img_general, NULL),
('211', 'Section D', 211, 'available', 2500, 'medium', 'General Merchandise', 'Great for personal care products and hygiene goods.', @img_general, NULL),
('212', 'Section D', 212, 'available', 2500, 'medium', 'General Merchandise', 'Corner stall with wide space for displaying varied merchandise.', @img_general, NULL),
('213', 'Section D', 213, 'available', 2500, 'medium', 'General Merchandise', 'Suitable for school supplies, notebooks, and art materials.', @img_general, NULL),
('214', 'Section D', 214, 'available', 2500, 'medium', 'General Merchandise', 'Excellent for seeds, gardening tools, and farm supplies.', @img_general, NULL),
('215', 'Section D', 215, 'available', 2500, 'medium', 'General Merchandise', 'Wide-open stall ideal for wholesale general goods.', @img_general, NULL),
('216', 'Section D', 216, 'reserved',  2500, 'medium', 'General Merchandise', 'Versatile stall for hardware, tools, and household items.', @img_general, NULL),
('217', 'Section D', 217, 'available', 2500, 'medium', 'General Merchandise', 'Ideal for selling electronics, phone accessories, and gadgets.', @img_general, NULL),
('218', 'Section D', 218, 'available', 2500, 'medium', 'General Merchandise', 'Perfect for kitchenware, cookware, and home essentials.', @img_general, NULL),
('219', 'Section D', 219, 'available', 2500, 'medium', 'General Merchandise', 'Great for personal care products and hygiene goods.', @img_general, NULL),
('220', 'Section D', 220, 'available', 2500, 'medium', 'General Merchandise', 'Corner stall with wide space for displaying varied merchandise.', @img_general, NULL),
('221', 'Section D', 221, 'available', 2500, 'medium', 'General Merchandise', 'Suitable for school supplies, notebooks, and art materials.', @img_general, NULL),
('222', 'Section D', 222, 'available', 2500, 'medium', 'General Merchandise', 'Excellent for seeds, gardening tools, and farm supplies.', @img_general, NULL),
('223', 'Section D', 223, 'available', 2500, 'medium', 'General Merchandise', 'Wide-open stall ideal for wholesale general goods.', @img_general, NULL),
('224', 'Section D', 224, 'available', 2500, 'medium', 'General Merchandise', 'Versatile stall for hardware, tools, and household items.', @img_general, NULL),
('225', 'Section D', 225, 'available', 2500, 'medium', 'General Merchandise', 'Ideal for selling electronics, phone accessories, and gadgets.', @img_general, NULL),
('226', 'Section D', 226, 'available', 2500, 'medium', 'General Merchandise', 'Perfect for kitchenware, cookware, and home essentials.', @img_general, NULL),
('227', 'Section D', 227, 'available', 2500, 'medium', 'General Merchandise', 'Great for personal care products and hygiene goods.', @img_general, NULL),
('228', 'Section D', 228, 'available', 2500, 'medium', 'General Merchandise', 'Corner stall with wide space for displaying varied merchandise.', @img_general, NULL),
('229', 'Section D', 229, 'available', 2500, 'medium', 'General Merchandise', 'Suitable for school supplies, notebooks, and art materials.', @img_general, NULL),
('230', 'Section D', 230, 'available', 2500, 'medium', 'General Merchandise', 'Excellent for seeds, gardening tools, and farm supplies.', @img_general, NULL),
('231', 'Section D', 231, 'available', 2500, 'medium', 'General Merchandise', 'Wide-open stall ideal for wholesale general goods.', @img_general, NULL),
('232', 'Section D', 232, 'available', 2500, 'medium', 'General Merchandise', 'Versatile stall for hardware, tools, and household items.', @img_general, NULL),
('233', 'Section D', 233, 'available', 2500, 'medium', 'General Merchandise', 'Ideal for selling electronics, phone accessories, and gadgets.', @img_general, NULL),
('234', 'Section D', 234, 'occupied',  2500, 'medium', 'General Merchandise', 'Perfect for kitchenware, cookware, and home essentials.', @img_general, NULL),
('235', 'Section D', 235, 'available', 2500, 'medium', 'General Merchandise', 'Great for personal care products and hygiene goods.', @img_general, NULL),
('236', 'Section D', 236, 'available', 2500, 'medium', 'General Merchandise', 'Corner stall with wide space for displaying varied merchandise.', @img_general, NULL),
('237', 'Section D', 237, 'available', 2500, 'medium', 'General Merchandise', 'Suitable for school supplies, notebooks, and art materials.', @img_general, NULL),
('238', 'Section D', 238, 'available', 2500, 'medium', 'General Merchandise', 'Excellent for seeds, gardening tools, and farm supplies.', @img_general, NULL),
('239', 'Section D', 239, 'available', 2500, 'medium', 'General Merchandise', 'Wide-open stall ideal for wholesale general goods.', @img_general, NULL),
('240', 'Section D', 240, 'available', 2500, 'medium', 'General Merchandise', 'Versatile stall for hardware, tools, and household items.', @img_general, NULL),
('241', 'Section D', 241, 'available', 2500, 'medium', 'General Merchandise', 'Ideal for selling electronics, phone accessories, and gadgets.', @img_general, NULL),
('242', 'Section D', 242, 'available', 2500, 'medium', 'General Merchandise', 'Perfect for kitchenware, cookware, and home essentials.', @img_general, NULL),
('243', 'Section D', 243, 'available', 2500, 'medium', 'General Merchandise', 'Great for personal care products and hygiene goods.', @img_general, NULL);

-- ─── Right Column: Stalls 244–300 (Mixed categories) ────────
INSERT INTO design_map_stalls (id, section, number, status, price, size, category, description, image_url, reservation_id) VALUES
('244', 'Right Column', 244, 'available', 1500, 'small',  'Cooked Food',           'Ideal for selling cooked meals, snacks, and Filipino dishes.', @img_food, NULL),
('245', 'Right Column', 245, 'available', 2500, 'medium', 'Vegetables & Fruits',   'Spacious stall perfect for fresh vegetables and seasonal produce.', @img_veggies, NULL),
('246', 'Right Column', 246, 'available', 2500, 'medium', 'Dry Goods & Groceries', 'Ideal for selling canned goods, condiments, and dry groceries.', @img_dry, NULL),
('247', 'Right Column', 247, 'available', 3500, 'large',  'Clothing & Apparel',    'Trendy location for ukay-ukay, ref items, and fashion pieces.', @img_clothing, NULL),
('248', 'Right Column', 248, 'available', 2500, 'medium', 'General Merchandise',   'Versatile stall for hardware, tools, and household items.', @img_general, NULL),
('249', 'Right Column', 249, 'available', 1500, 'small',  'Cooked Food',           'Perfect spot for a carinderia or food stall near the main aisle.', @img_food, NULL),
('250', 'Right Column', 250, 'available', 2500, 'medium', 'Vegetables & Fruits',   'Conveniently located near the entrance for easy customer access.', @img_veggies, NULL),
('251', 'Right Column', 251, 'available', 2500, 'medium', 'Dry Goods & Groceries', 'Large stall suitable for wholesale and retail dry goods.', @img_dry, NULL),
('252', 'Right Column', 252, 'available', 3500, 'large',  'Clothing & Apparel',    'Perfect for selling everyday clothing and accessories.', @img_clothing, NULL),
('253', 'Right Column', 253, 'available', 2500, 'medium', 'General Merchandise',   'Ideal for selling electronics, phone accessories, and gadgets.', @img_general, NULL),
('254', 'Right Column', 254, 'available', 1500, 'small',  'Cooked Food',           'High-traffic location great for fast food and ready-to-eat items.', @img_food, NULL),
('255', 'Right Column', 255, 'available', 2500, 'medium', 'Vegetables & Fruits',   'Great for fruits, vegetables, herbs, and fresh condiments.', @img_veggies, NULL),
('256', 'Right Column', 256, 'available', 2500, 'medium', 'Dry Goods & Groceries', 'Perfect for rice, flour, sugar, salt, and pantry essentials.', @img_dry, NULL),
('257', 'Right Column', 257, 'available', 3500, 'large',  'Clothing & Apparel',    'Ideal for school uniforms, casual wear, and workwear.', @img_clothing, NULL),
('258', 'Right Column', 258, 'available', 2500, 'medium', 'General Merchandise',   'Perfect for kitchenware, cookware, and home essentials.', @img_general, NULL),
('259', 'Right Column', 259, 'available', 1500, 'small',  'Cooked Food',           'Corner stall with extra space for cooking equipment and display.', @img_food, NULL),
('260', 'Right Column', 260, 'available', 2500, 'medium', 'Vegetables & Fruits',   'Well-ventilated space ideal for fresh tropical fruits.', @img_veggies, NULL),
('261', 'Right Column', 261, 'available', 2500, 'medium', 'Dry Goods & Groceries', 'Great for spices, seasonings, and cooking ingredients.', @img_dry, NULL),
('262', 'Right Column', 262, 'available', 3500, 'large',  'Clothing & Apparel',    'Great spot for selling bags, shoes, and fashion accessories.', @img_clothing, NULL),
('263', 'Right Column', 263, 'available', 2500, 'medium', 'General Merchandise',   'Great for personal care products and hygiene goods.', @img_general, NULL),
('264', 'Right Column', 264, 'available', 1500, 'small',  'Cooked Food',           'Suitable for selling breakfast meals, kakanin, and beverages.', @img_food, NULL),
('265', 'Right Column', 265, 'available', 2500, 'medium', 'Vegetables & Fruits',   'Corner stall with wide display area for colorful produce.', @img_veggies, NULL),
('266', 'Right Column', 266, 'available', 2500, 'medium', 'Dry Goods & Groceries', 'Corner location with high foot traffic, ideal for grocery items.', @img_dry, NULL),
('267', 'Right Column', 267, 'available', 3500, 'large',  'Clothing & Apparel',    'Corner stall with extra space for hanging clothes and display.', @img_clothing, NULL),
('268', 'Right Column', 268, 'available', 2500, 'medium', 'General Merchandise',   'Corner stall with wide space for displaying varied merchandise.', @img_general, NULL),
('269', 'Right Column', 269, 'available', 1500, 'small',  'Cooked Food',           'Great for silog meals, merienda, and affordable daily lunches.', @img_food, NULL),
('270', 'Right Column', 270, 'available', 2500, 'medium', 'Vegetables & Fruits',   'Suitable for exotic fruits, organic veggies, and fresh herbs.', @img_veggies, NULL),
('271', 'Right Column', 271, 'available', 2500, 'medium', 'Dry Goods & Groceries', 'Suitable for noodles, crackers, biscuits, and packaged foods.', @img_dry, NULL),
('272', 'Right Column', 272, 'available', 3500, 'large',  'Clothing & Apparel',    'High-visibility location for fashion retail and trendy items.', @img_clothing, NULL),
('273', 'Right Column', 273, 'available', 2500, 'medium', 'General Merchandise',   'Suitable for school supplies, notebooks, and art materials.', @img_general, NULL),
('274', 'Right Column', 274, 'available', 1500, 'small',  'Cooked Food',           'Prime location for barbecue, grilled items, and pulutan.', @img_food, NULL),
('275', 'Right Column', 275, 'available', 2500, 'medium', 'Vegetables & Fruits',   'Near the wet section, ideal for root crops and leafy greens.', @img_veggies, NULL),
('276', 'Right Column', 276, 'available', 2500, 'medium', 'Dry Goods & Groceries', 'Excellent for coffee, sugar, and everyday household needs.', @img_dry, NULL),
('277', 'Right Column', 277, 'available', 3500, 'large',  'Clothing & Apparel',    "Suitable for children's clothing, school supplies, and toys.", @img_clothing, NULL),
('278', 'Right Column', 278, 'available', 2500, 'medium', 'General Merchandise',   'Excellent for seeds, gardening tools, and farm supplies.', @img_general, NULL),
('279', 'Right Column', 279, 'available', 1500, 'small',  'Cooked Food',           'Excellent for baked goods, pastries, and Filipino desserts.', @img_food, NULL),
('280', 'Right Column', 280, 'available', 2500, 'medium', 'Vegetables & Fruits',   'Prime spot for selling locally sourced farm produce.', @img_veggies, NULL),
('281', 'Right Column', 281, 'available', 2500, 'medium', 'Dry Goods & Groceries', 'Wide display space for organizing dry goods and groceries.', @img_dry, NULL),
('282', 'Right Column', 282, 'available', 3500, 'large',  'Clothing & Apparel',    'Excellent for local designer pieces and handcrafted goods.', @img_clothing, NULL),
('283', 'Right Column', 283, 'available', 2500, 'medium', 'General Merchandise',   'Wide-open stall ideal for wholesale general goods.', @img_general, NULL),
('284', 'Right Column', 284, 'available', 1500, 'small',  'Cooked Food',           'Ideal for selling cooked meals, snacks, and Filipino dishes.', @img_food, NULL),
('285', 'Right Column', 285, 'available', 2500, 'medium', 'Vegetables & Fruits',   'Spacious stall perfect for fresh vegetables and seasonal produce.', @img_veggies, NULL),
('286', 'Right Column', 286, 'available', 2500, 'medium', 'Dry Goods & Groceries', 'Ideal for selling canned goods, condiments, and dry groceries.', @img_dry, NULL),
('287', 'Right Column', 287, 'available', 3500, 'large',  'Clothing & Apparel',    'Trendy location for ukay-ukay, ref items, and fashion pieces.', @img_clothing, NULL),
('288', 'Right Column', 288, 'available', 2500, 'medium', 'General Merchandise',   'Versatile stall for hardware, tools, and household items.', @img_general, NULL),
('289', 'Right Column', 289, 'available', 1500, 'small',  'Cooked Food',           'Perfect spot for a carinderia or food stall near the main aisle.', @img_food, NULL),
('290', 'Right Column', 290, 'available', 2500, 'medium', 'Vegetables & Fruits',   'Conveniently located near the entrance for easy customer access.', @img_veggies, NULL),
('291', 'Right Column', 291, 'available', 2500, 'medium', 'Dry Goods & Groceries', 'Large stall suitable for wholesale and retail dry goods.', @img_dry, NULL),
('292', 'Right Column', 292, 'available', 3500, 'large',  'Clothing & Apparel',    'Perfect for selling everyday clothing and accessories.', @img_clothing, NULL),
('293', 'Right Column', 293, 'available', 2500, 'medium', 'General Merchandise',   'Ideal for selling electronics, phone accessories, and gadgets.', @img_general, NULL),
('294', 'Right Column', 294, 'available', 1500, 'small',  'Cooked Food',           'High-traffic location great for fast food and ready-to-eat items.', @img_food, NULL),
('295', 'Right Column', 295, 'available', 2500, 'medium', 'Vegetables & Fruits',   'Great for fruits, vegetables, herbs, and fresh condiments.', @img_veggies, NULL),
('296', 'Right Column', 296, 'available', 2500, 'medium', 'Dry Goods & Groceries', 'Perfect for rice, flour, sugar, salt, and pantry essentials.', @img_dry, NULL),
('297', 'Right Column', 297, 'available', 3500, 'large',  'Clothing & Apparel',    'Ideal for school uniforms, casual wear, and workwear.', @img_clothing, NULL),
('298', 'Right Column', 298, 'available', 2500, 'medium', 'General Merchandise',   'Perfect for kitchenware, cookware, and home essentials.', @img_general, NULL),
('299', 'Right Column', 299, 'available', 1500, 'small',  'Cooked Food',           'Corner stall with extra space for cooking equipment and display.', @img_food, NULL),
('300', 'Right Column', 300, 'available', 2500, 'medium', 'Vegetables & Fruits',   'Well-ventilated space ideal for fresh tropical fruits.', @img_veggies, NULL);

-- ─── Corner Stalls ──────────────────────────────────────────
INSERT INTO design_map_stalls (id, section, number, status, price, size, category, description, image_url, reservation_id) VALUES
('A1',  'Corner A', 0, 'available', 4500, 'corner', 'General Merchandise', 'Versatile stall for hardware, tools, and household items.', @img_general, NULL),
('A2',  'Corner A', 0, 'available', 4500, 'corner', 'General Merchandise', 'Ideal for selling electronics, phone accessories, and gadgets.', @img_general, NULL),
('A3',  'Corner A', 0, 'available', 4500, 'corner', 'General Merchandise', 'Perfect for kitchenware, cookware, and home essentials.', @img_general, NULL),
('A4',  'Corner A', 0, 'available', 4500, 'corner', 'General Merchandise', 'Great for personal care products and hygiene goods.', @img_general, NULL),
('A5',  'Corner A', 0, 'available', 4500, 'corner', 'General Merchandise', 'Corner stall with wide space for displaying varied merchandise.', @img_general, NULL),
('B1',  'Corner B', 0, 'available', 4500, 'corner', 'General Merchandise', 'Suitable for school supplies, notebooks, and art materials.', @img_general, NULL),
('B2',  'Corner B', 0, 'available', 4500, 'corner', 'General Merchandise', 'Excellent for seeds, gardening tools, and farm supplies.', @img_general, NULL),
('B3',  'Corner B', 0, 'available', 4500, 'corner', 'General Merchandise', 'Wide-open stall ideal for wholesale general goods.', @img_general, NULL),
('B4',  'Corner B', 0, 'available', 4500, 'corner', 'General Merchandise', 'Versatile stall for hardware, tools, and household items.', @img_general, NULL),
('C1',  'Corner C', 0, 'available', 4500, 'corner', 'General Merchandise', 'Ideal for selling electronics, phone accessories, and gadgets.', @img_general, NULL),
('C2',  'Corner C', 0, 'available', 4500, 'corner', 'General Merchandise', 'Perfect for kitchenware, cookware, and home essentials.', @img_general, NULL),
('C3',  'Corner C', 0, 'available', 4500, 'corner', 'General Merchandise', 'Great for personal care products and hygiene goods.', @img_general, NULL),
('C4',  'Corner C', 0, 'available', 4500, 'corner', 'General Merchandise', 'Corner stall with wide space for displaying varied merchandise.', @img_general, NULL),
('D36', 'Corner D', 0, 'available', 4500, 'corner', 'General Merchandise', 'Versatile stall for hardware, tools, and household items.', @img_general, NULL),
('D37', 'Corner D', 0, 'available', 4500, 'corner', 'General Merchandise', 'Ideal for selling electronics, phone accessories, and gadgets.', @img_general, NULL),
('D38', 'Corner D', 0, 'available', 4500, 'corner', 'General Merchandise', 'Perfect for kitchenware, cookware, and home essentials.', @img_general, NULL),
('D39', 'Corner D', 0, 'available', 4500, 'corner', 'General Merchandise', 'Great for personal care products and hygiene goods.', @img_general, NULL),
('D5',  'Corner D', 0, 'available', 4500, 'corner', 'General Merchandise', 'Suitable for school supplies, notebooks, and art materials.', @img_general, NULL),
('D6',  'Corner D', 0, 'available', 4500, 'corner', 'General Merchandise', 'Excellent for seeds, gardening tools, and farm supplies.', @img_general, NULL);
